# Generated by Django 6.0.2 on 2026-02-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='ชื่อหุ้น SET50')),
                ('company_name', models.CharField(max_length=100)),
                ('historical_return', models.FloatField(default=0.08, help_text='Expected annual return')),
                ('historical_volatility', models.FloatField(default=0.15, help_text='Annual standard deviation')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='เป้าหมาย (บาท)')),
                ('monthly_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินลงทุนต่อเดือน (บาท)')),
                ('duration_months', models.IntegerField(verbose_name='ระยะเวลา (เดือน)')),
                ('selected_asset', models.CharField(default='SET50', max_length=50, verbose_name='สินทรัพย์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('is_ga_optimized', models.BooleanField(default=True)),
                ('allocation_json', models.JSONField(help_text='Store optimal weights from GA')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.investmentplan')),
            ],
        ),
    ]
