# Generated by Django 6.0.2 on 2026-02-24 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioresult',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='historical_return',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='historical_volatility',
        ),
        migrations.AddField(
            model_name='stock',
            name='is_set50',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_investment', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('selected_stocks', models.TextField(default='ADVANC,AOT,CPALL,KBANK,PTT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentPlan',
        ),
        migrations.DeleteModel(
            name='PortfolioResult',
        ),
    ]
