# Generated by Django 6.0.2 on 2026-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_portfolioresult_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='duration_years',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userplan',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12),
        ),
    ]
