# Generated by Django 6.0.2 on 2026-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userplan_duration_years_userplan_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='เปลี่ยนแปลง'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคาล่าสุด'),
        ),
        migrations.AddField(
            model_name='stock',
            name='percent_change',
            field=models.FloatField(default=0.0, verbose_name='% เปลี่ยนแปลง'),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด'),
        ),
    ]
