# Generated by Django 6.0.2 on 2026-06-03 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stock_change_stock_last_price_stock_percent_change_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCAPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแผน')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('monthly_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินลงทุนรายเดือน')),
                ('duration_years', models.IntegerField(verbose_name='ระยะเวลา (ปี)')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='เป้าหมายทางการเงิน')),
                ('selected_stocks', models.TextField(verbose_name='หุ้นที่เลือก')),
                ('expected_return', models.FloatField(verbose_name='ผลตอบแทนคาดหวัง (%)')),
                ('risk_level', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], max_length=20, verbose_name='ระดับความเสี่ยง')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แผน DCA สำเร็จรูป',
                'verbose_name_plural': 'แผน DCA สำเร็จรูป',
            },
        ),
        migrations.AddField(
            model_name='userplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplan',
            name='last_expected_return',
            field=models.FloatField(blank=True, null=True, verbose_name='ผลตอบแทนคาดหวัง'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='last_optimized_weights',
            field=models.JSONField(blank=True, null=True, verbose_name='ผลลัพธ์ GA ล่าสุด'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='last_sharpe_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Sharpe Ratio'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='duration_years',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='monthly_investment',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='เกี่ยวกับตัวเอง')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('preferred_language', models.CharField(choices=[('th', 'ไทย'), ('en', 'English')], default='th', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='เดือนการลงทุน')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงินที่ลงทุน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'บันทึกการลงทุน',
                'verbose_name_plural': 'บันทึกการลงทุน',
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
