# Generated by Django 6.0.2 on 2026-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dcapreset_userplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='last_chart_data',
            field=models.JSONField(blank=True, null=True, verbose_name='ข้อมูลกราฟผลลัพธ์ล่าสุด'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='last_chart_labels',
            field=models.JSONField(blank=True, null=True, verbose_name='ป้ายกราฟผลลัพธ์ล่าสุด'),
        ),
    ]
