# Generated by Django 6.0.2 on 2026-06-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userplan_last_chart_data_userplan_last_chart_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GAResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return', models.FloatField(blank=True, null=True)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('weights', models.JSONField(blank=True, null=True)),
                ('chart_labels', models.JSONField(blank=True, null=True)),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('final_portfolio_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GA Result Snapshot',
                'verbose_name_plural': 'GA Result Snapshots',
                'ordering': ['-saved_at'],
            },
        ),
    ]
